name: CI
on:
  push:
    branches:
      - "**"
env:
  WSS_URL: ws://127.0.0.1:9955

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run fmt

  test_basic:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          pnpm install   
          pnpm run build
      - name: Run standard dev test
        run: |
          cd test
          bun moonwall test basic

  test_tanssi:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build like before
        run: |
          pnpm install  
          pnpm run build
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Download tanssi binary
        run: |
          cd test
          bun moonwall download tanssi-node latest ./tmp
      - name: Run standard dev test
        run: |
          cd test
          bun moonwall test dev_tanssi

  test_dev:
    runs-on: ubuntu-latest
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        suite: ["dev_test", "dev_multi", "dev_seq"]
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build like before
        run: |
          pnpm install  
          pnpm run build
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Download moonbeam binary
        run: |
          cd test
          bun moonwall download moonbeam latest ./tmp
      - name: Run ${{matrix.suite}} dev test
        run: |
          cd test
          bun moonwall test ${{matrix.suite}}

  test_chopsticks:
    runs-on: ubuntu-latest
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        suite: ["chopsticks", "multi_chopsticks"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build like before
        run: |
          pnpm install   
          pnpm run build
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run ${{matrix.suite}}
        run: |
          cd test
          bun moonwall test ${{matrix.suite}}

      # disabled until we have an available instance of moonscope running
      # - name: Use Send Report Action
      #   if: always()
      #   uses: ./.github/send-report-action
      #   with:
      #     table: dev_reports
      #     moonwallenv: moonwall_chopsticks
      #     report_file_path: tmp/testReports.json
      #     moonscope: "https://moonscope.boo:3345"

  test_readonly:
    runs-on: ubuntu-latest
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        suite: ["eth_test", "viem_test"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build like before
        run: |
          pnpm install   
          pnpm run build
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run standard ${{matrix.suite}}}
        run: |
          cd test
          bun moonwall test ${{matrix.suite}}
      #  disabled until web3.js fix their stuff
      # - name: Run standard web3 run
      #   run: bun moonwall test web3_test

  test_zombie:
    runs-on: ubuntu-latest
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        suite: ["zombie_test", "zombie_multi_para"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          pnpm install   
          pnpm run build
      - name: Download binaries
        run: |
          cd test
          bun moonwall download moonbeam latest ./tmp

          # Change these to latest once MB is compatible with 1.2.0
          bun moonwall download polkadot 1.1.0 ./tmp
          bun moonwall download polkadot-execute-worker 1.1.0 ./tmp
          bun moonwall download polkadot-prepare-worker 1.1.0 ./tmp
      - name: Run ${{matrix.suite}}
        run: |
          cd test
          bun moonwall test ${{matrix.suite}}
