name: CI
on:
  push:
    branches:
      - "**"
env:
  WSS_URL: ws://127.0.0.1:9955

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install  --no-frozen-lockfile
      - run: pnpm run lint && pnpm run build

  test_basic:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          pnpm install  --no-frozen-lockfile
          pnpm run lint && pnpm run build
      - name: Run standard dev test
        run: bun moonwall test basic

  test_dev:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build like before
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run lint && pnpm run build
      - name: Download moonbeam binary
        run: bun moonwall download moonbeam latest ./tmp
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run standard dev test
        run: bun moonwall test dev_test
      - name: Run parallel dev test
        run: bun moonwall test dev_multi
      - name: Run sequential dev test
        run: bun moonwall test dev_seq

  test_chopsticks:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build like before
        run: |
          pnpm install  --no-frozen-lockfile
          pnpm run lint && pnpm run build
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run standard chopsticks run
        run: bun moonwall test chopsticks

  test_readonly:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Build like before
        run: |
          pnpm install  --no-frozen-lockfile
          pnpm run lint && pnpm run build
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run standard ethers run
        run: bun moonwall test eth_test
      - name: Run standard viem run
        run: bun moonwall test viem_test
      #  disabled until web3.js fix their stuff
      # - name: Run standard web3 run
      #   run: bun moonwall test web3_test

  test_zombie:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          pnpm install  --no-frozen-lockfile
          pnpm run lint && pnpm run build
      - name: Download binaries
        run: |
          bun moonwall download moonbeam latest ./tmp
          bun moonwall download polkadot latest ./tmp
      - name: Run standard zombie test
        run: bun moonwall test zombie_test

  test_multi_zombie:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          pnpm install  --no-frozen-lockfile
          pnpm run lint && pnpm run build
      - name: Download binaries
        run: |
          bun moonwall download moonbeam latest ./tmp
          bun moonwall download polkadot latest ./tmp
      - name: Run multi zombie test
        run: bun moonwall test zombie_multi_para
