name: CI
on:
  push:
    branches:
      - "**"
env:
  WSS_URL: ws://127.0.0.1:9955

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun fmt

  test_basic:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          bun install   
          bun run build
      - name: Run standard dev test
        run: |
          cd test
          bun moonwall test basic
  test_tanssi:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          bun install  
          bun run build
      - name: Download tanssi binary
        run: |
          cd test
          bun moonwall download tanssi-node latest ./tmp
      - name: Run standard dev test
        run: |
          cd test
          bun moonwall test dev_tanssi

  test_dev:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          bun install  
          bun run build
      - name: Download moonbeam binary
        run: |
          cd test
          bun moonwall download moonbeam latest ./tmp
      - name: Run standard dev test
        run: |
          cd test
          bun moonwall test dev_test
      - name: Run parallel dev test
        run: |
          cd test
          bun moonwall test dev_multi
      - name: Run sequential dev test
        run: |
          cd test
          bun moonwall test dev_seq

  test_chopsticks:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          bun install   
          bun run build
      - name: Run standard chopsticks run
        run: |
          cd test
          bun moonwall test chopsticks

      # disabled until we have an available instance of moonscope running
      # - name: Use Send Report Action
      #   if: always()
      #   uses: ./.github/send-report-action
      #   with:
      #     table: dev_reports
      #     moonwallenv: moonwall_chopsticks
      #     report_file_path: tmp/testReports.json
      #     moonscope: "https://moonscope.boo:3345"

  test_readonly:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          bun install   
          bun run build
      - name: Run standard ethers run
        run: |
          cd test
          bun moonwall test eth_test
      - name: Run standard viem run
        run: |
          cd test
          bun moonwall test viem_test
      #  disabled until web3.js fix their stuff
      # - name: Run standard web3 run
      #   run: bun moonwall test web3_test

  test_zombie:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          bun install   
          bun run build
      - name: Download binaries
        run: |
          cd test
          bun moonwall download moonbeam latest ./tmp
          bun moonwall download polkadot latest ./tmp
          bun moonwall download polkadot-execute-worker latest ./tmp
          bun moonwall download polkadot-prepare-worker latest ./tmp
      - name: Run standard zombie test
        run: |
          cd test
          bun moonwall test zombie_test

  test_multi_zombie:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build like before
        run: |
          bun install   
          bun run build
      - name: Download binaries
        run: |
          cd test
          bun moonwall download moonbeam latest ./tmp
          bun moonwall download polkadot latest ./tmp
          bun moonwall download polkadot-execute-worker latest ./tmp
          bun moonwall download polkadot-prepare-worker latest ./tmp
      - name: Run multi zombie test
        run: |
          cd test
          bun moonwall test zombie_multi_para
